# Generated by Django 3.1.1 on 2020-09-25 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 9, 25, 16, 39, 12, 244294, tzinfo=utc))),
            ],
        ),
    ]
